app = 'arkaans-copilot'
primary_region = 'cdg'

[build]

[env]
  NODE_ENV = 'production'

[machines]
  auto_stop = "off"
  auto_start = false
  min_count = 1

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
